version: "3"
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
  compiler:
    image: rafaelkuhn/compiler
    container_name: compiler
    ports:
      - "8000:8000"
  