version: "3"
services:
  backend:
    build: .
    container_name: rafaelkuhn/backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - default
  compiler:
    image: rafaelkuhn/compiler
    container_name: compiler
    networks:
      - default
networks:
  default:
    driver: bridge
